### ISSUE TITLE
Add option to create comment at the beginning of the comment line instead of center.

### ISSUE THREAD

**Issue by ZenMittal** [stackbreak/comment-divider#1]
Center-aligned comment words are hard to read in comparison to when comment words are aligned at the left, close to the beginning of the line.

Also, another cool feature would be making a small one line comment (without any extra decoration) as writing even simple comments in HTML and CSS can be made easier this way.

**Comment by stackbreak** [comment]
@ZenMittal, thanks for your suggestions!
This is great idea, I will implement option for left/right alignment on the next update.

About second point: can you show example of input and expected output ?
