### ISSUE TITLE
left/right align for "line"

### ISSUE THREAD

**Issue by ysBach** [stackbreak/comment-divider#15]
The align from the below settings do not work.
```
"comment-divider.subHeaderFiller": "-",
"comment-divider.subHeaderHeight": "line",
"comment-divider.subHeaderTransform": "none",
"comment-divider.subHeaderAlign": "left",
```

It gives
```python
# --------------------------------- comment --------------------------------- #
```
in python, where I expected
```python
# comment ------------------------------------------------------------------- #
```
Is this an intended behavior?

**Comment by stackbreak** [comment]
Hi @ysBach !
It seems like you have a typo in settings keys. You should use "_sub**h**eader_" instead of "_sub**H**eader_".

**Comment by ysBach** [comment]
@stackbreak Oh, my bad..!
Thanks for the reply. It now works like a charm :)
