### ISSUE TITLE
Comment starts with a specific character

### ISSUE THREAD

**Issue by ysBach** [stackbreak/comment-divider#16]
I am using commend-divider with [Better Comments](https://github.com/aaron-bond/better-comments) (to sometimes put, e.g., ``*`` to highlight the comment).

What I want is to automatically make 
```
# *************************************************************************** #
# *                             MINMAX CLIPPING                             * #
# *************************************************************************** #
```
which will automatically be highlighted. 

IMHO, an addition of the feature such as
```
"comment-divider.mainHeaderStarter": "*",
"comment-divider.mainHeaderEnder": "*",
```
can be useful. How do you think...?

**Comment by stackbreak** [comment]
Sorry, it will not be realized.
I take the approach that config/API for users should be as simple as possible. In my opinion, this is a very rare case, make things more complicated.
