### ISSUE TITLE
Add another divider level

### ISSUE THREAD

**Issue by kquiring** [stackbreak/comment-divider#2]
Today, "main" and "divider" are defined.  I use a slightly deeper divider structure.  

/* ======================= 
   ALL CAPS
/* ======================= */

/* ---------------------------------------
  Title Case
/* --------------------------------------- */
 
/* --------------- Title Case ------------ */

I can almost do this today, but I can't do the middle one because only one "main" style can be defined at a time.  

Accomplishing this scheme also means a setting for each level indicating case conversion (ie, all caps, title case, unchanged).  Title case isn't terribly important, but I'd need the option for a main-style header to not convert to all caps.

**Comment by stackbreak** [comment]
@kquiring thanks for feedback!
I will extend settings for both types of dividers, special for such cases.
