### ISSUE TITLE
Add feature for indented code

### ISSUE THREAD

**Issue by AndreasLuckert** [stackbreak/comment-divider#25]
It'd be nice if the tool could recognize two things:

1. **Language-specific horizontal ruler-extension limits** defined in the `settings.json` - file:
```
"[python]": {
        "editor.rulers": [
            80,
            120
        ]
    }
```

2. **Indentation according to current code**:
Instead of heaving to tab it over and then accept that the ruler exceeds the vertical limits like so ...
```
# ------------------------------- Some function ------------------------------ #
def func():

    # ------------------------------- Sub-function ------------------------------- #
    def sub_func():
        pass
```

... it'd be awesome of the extension _calculated automatically the difference between the indentation and the vertical right limit_, which would lead to following result:
```
# ------------------------------- Some function ------------------------------ #
def func():

    # ----------------------------- Sub-function ----------------------------- #
    def sub_func():
        pass
```

**Comment by stackbreak** [comment]
@AndreasLuckert 
[released](https://github.com/stackbreak/comment-divider/blob/master/CHANGELOG.md#040---2020-05-18)
