### ISSUE TITLE
[Request] Add option to use double slash (//) for Less/Scss/Sass preprocessor comments

### ISSUE THREAD

**Issue by thedelk** [stackbreak/comment-divider#3]
First, I'd like to thank you for this fantastic plugin. It's little things like this that make coding so much easier and leave me with less to worry about.

It's a humble request, but I would love to be able to use the `//` comment indicator instead of the comment lines being wrapped in `/*...*/`.

For example, instead of:

```
/* Example ------------------------------------------------------------------ */
```

I would like to be able to change it to:

```
// Example --------------------------------------------------------------------
```

I know it's minor, but I never write vanilla CSS so I've become quite attached to my slashes. :sweat_smile:

Cheers, and thank you again!

**Comment by stackbreak** [comment]
@thedelk Thanks for your feedback!
Good suggestion, I will include it into next release.

**Comment by the-nicolas** [comment]
Same problem for *.vue files, the <script> part gets not treated as javascript (or in my case typescript).

Thanks a lot, I love that simple and good extension realy.

**Comment by ctokun** [comment]
Did this end up being implemented? Can't figure out the setting that would change it. Love the extension and would benefit from the option. SCSS keeps all comments beginning with /* into CSS and drops comments beginning with //, so changing from /* to // would be helpful.

**Comment by stackbreak** [comment]
@ctokun 

[released now](https://github.com/stackbreak/comment-divider/blob/master/CHANGELOG.md#030---2020-12-07)
