### ISSUE TITLE
[Request] Folding support

### ISSUE THREAD

**Issue by ghadesi** [stackbreak/comment-divider#56]
On VSCode, by the region keyword, we can divide our codes into multiple sections and fold them easily. Can you add this feature? It is easy to just add two keywords at the beginning of the comment generator.
convert
```python
 # ----------------------------------- code ----------------------------------- #
```
to  
```python
#region ----------------------------------- code ----------------------------------- #
```
and 
```python
# ---------------------------------------------------------------------------- #
```

```python
#endregion ---------------------------------------------------------------------------- #
```

**Comment by stackbreak** [comment]
related to https://github.com/stackbreak/comment-divider/issues/54 : 
It looks interesting, I will try to find time to research a liitle about.
